default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: booksproject

test:
  <<: *default
  database: booksproject


production:
  primary: &primary_production
    <<: *default
    database: books_project_production
    username: books_project
    password: <%= ENV["BOOKS_PROJECT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: books_project_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: books_project_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: books_project_production_cable
    migrations_paths: db/cable_migrate
